on: push
name: Really cool demo
jobs:
    push-to-azure:
        name: :Publish Azure resources
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              name: checkout code
            - uses: azure/login@v2 
              with:
                creds: ${{secrets.AZURE_CREDENTIALS }}
            - run: |
                az webapp up \
                --name sydneymarchthirty \
                --plan marchplan \
                --os-type linux \
                --runtime DOTNET:6.0
              name: Push app content to App service    

    build-job:
        name: Build .NET project
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/dotnet/sdk:8.0
        steps: 
            - run: dotnet --version
              name: Check .NET version
            - uses: actions/checkout@v3 
              name: Checkout code
            - run: |
                dotnet publish \
                --configuration Release \
                --output out
              name: Publish .NET web app
            - uses: actions/upload-artifact@v3
              name: Upload publish output
              with:
                name: web app
                path: out     