on: push
name: Really cool demo
jobs:
    build-job:
        name: Build .NET project
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/dotnet/sdk:8.0
        steps: 
            - run: dotnet --version
              name: Check .NET version